import { Router } from "express";
import * as controller from '../controllers/LDSM004Controller';
import authenticationMiddleware from '../middlewares/authenticationMiddleware'

const LDSM004Route = Router()

// C1CES007Route.route('/getGroupPlant').post(authenticationMiddleware.bearer, authenticationMiddleware.reader, getGroupPlant);
LDSM004Route.route('/getProcess').post(authenticationMiddleware.bearer, controller.GetProcess);
LDSM004Route.route('/getTataDate').post(authenticationMiddleware.bearer, controller.getTataDate);
LDSM004Route.route('/getBatchTonage').post(authenticationMiddleware.bearer, controller.GetBatchTonage);
LDSM004Route.route('/getBatchDtl').post(authenticationMiddleware.bearer, controller.GetBatchDtl);
LDSM004Route.route('/getBatchInfo').post(authenticationMiddleware.bearer, controller.GetBatchInfo);
LDSM004Route.route('/getODIA').post(authenticationMiddleware.bearer, controller.GetODIA);
LDSM004Route.route('/getReverseMerge').post(authenticationMiddleware.bearer, controller.getReverseMerge);
LDSM004Route.route('/callUNMERGE').post(authenticationMiddleware.bearer, controller.callUNMERGE);
LDSM004Route.route('/getPalletPlantCount').post(authenticationMiddleware.bearer, controller.GetPalletPlantCount);
LDSM004Route.route('/getPrDateShift').post(authenticationMiddleware.bearer, controller.getPrDateShift);
LDSM004Route.route('/getAdjBatch').post(authenticationMiddleware.bearer, controller.getAdjBatch);
LDSM004Route.route('/getLblInfo').post(authenticationMiddleware.bearer, controller.GetLblInfo);
LDSM004Route.route('/getPdiDtl').post(authenticationMiddleware.bearer, controller.GetPdiDtl);
LDSM004Route.route('/getBatchDspl').post(authenticationMiddleware.bearer, controller.GetBatchDspl);
LDSM004Route.route('/getWtAdjust').post(authenticationMiddleware.bearer, controller.GetWtAdjust);
LDSM004Route.route('/getOrderCheck').post(authenticationMiddleware.bearer, controller.OrderCheck);
LDSM004Route.route('/getPlantPdf').post(authenticationMiddleware.bearer, controller.GetPlantPdf);
LDSM004Route.route('/getCntProcPlant').post(authenticationMiddleware.bearer, controller.CntProcPlant);
LDSM004Route.route('/getReverse_Grn').post(authenticationMiddleware.bearer, controller.Reverse_Grn);
LDSM004Route.route('/getVal').post(authenticationMiddleware.bearer, controller.GetVal);
LDSM004Route.route('/getMResWT').post(authenticationMiddleware.bearer, controller.GetMResWT);
LDSM004Route.route('/getScrapPlant').post(authenticationMiddleware.bearer, controller.GetScrapPlant);
LDSM004Route.route('/getBatch_Chk').post(authenticationMiddleware.bearer, controller.Batch_Chk);
LDSM004Route.route('/getModifyBatch').post(authenticationMiddleware.bearer, controller.ModifyBatch);
LDSM004Route.route('/getBatchID').post(authenticationMiddleware.bearer, controller.GetBatchID);
LDSM004Route.route('/getChkBatchID').post(authenticationMiddleware.bearer, controller.ChkBatchID);
LDSM004Route.route('/getOrdDtls').post(authenticationMiddleware.bearer, controller.getOrdDtls);
LDSM004Route.route('/getQltyGrade').post(authenticationMiddleware.bearer, controller.GetQltyGrade);
LDSM004Route.route('/getCheckBatchAvailibility').post(authenticationMiddleware.bearer, controller.CheckBatchAvailibility);
LDSM004Route.route('/getWithoutRecordingBypass').post(authenticationMiddleware.bearer, controller.WithoutRecordingBypass);
LDSM004Route.route('/getPlanNM').post(authenticationMiddleware.bearer, controller.PlanNM);
LDSM004Route.route('/getProcLine').post(authenticationMiddleware.bearer, controller.GetProcLine);
LDSM004Route.route('/getCustNm').post(authenticationMiddleware.bearer, controller.getCustNm);
LDSM004Route.route('/getSecRsns').post(authenticationMiddleware.bearer, controller.getSecRsns);
LDSM004Route.route('/getScrRsnCD').post(authenticationMiddleware.bearer, controller.GetScrRsnCD);
LDSM004Route.route('/getSlitSts').post(authenticationMiddleware.bearer, controller.GetSlitSts);
LDSM004Route.route('/getRsnCat').post(authenticationMiddleware.bearer, controller.GetRsnCat);
LDSM004Route.route('/getHoldRsn').post(authenticationMiddleware.bearer, controller.GetHoldRsn);
LDSM004Route.route('/getScrRsnCat').post(authenticationMiddleware.bearer, controller.GetScrRsnCat);
LDSM004Route.route('/getScrMat').post(authenticationMiddleware.bearer, controller.GetScrMat);
LDSM004Route.route('/getInvPerc').post(authenticationMiddleware.bearer, controller.InvPerc);
LDSM004Route.route('/getOrderRnage').post(authenticationMiddleware.bearer, controller.OrderRnage);
LDSM004Route.route('/getCheckRange').post(authenticationMiddleware.bearer, controller.CheckRange);
LDSM004Route.route('/grade').post(authenticationMiddleware.bearer, controller.Grade);
LDSM004Route.route('/getP_Insert').post(authenticationMiddleware.bearer, controller.P_Insert);
LDSM004Route.route('/getP_Insert_Wires').post(authenticationMiddleware.bearer, controller.P_Insert_Wires);
LDSM004Route.route('/getMCoilList').post(authenticationMiddleware.bearer, controller.GetMCoilList);
LDSM004Route.route('/getDaugherCoil').post(authenticationMiddleware.bearer, controller.GetDaugherCoil);
LDSM004Route.route('/getScrapWiresDtl').post(authenticationMiddleware.bearer, controller.GetScrapWiresDtl);
LDSM004Route.route('/getDelWorkInst').post(authenticationMiddleware.bearer, controller.DelWorkInst);
LDSM004Route.route('/getInsertLabel').post(authenticationMiddleware.bearer, controller.InsertLabel);
LDSM004Route.route('/getInsertScr').post(authenticationMiddleware.bearer, controller.InsertScr);
LDSM004Route.route('/getCallProcedureSCRAPPOST').post(authenticationMiddleware.bearer, controller.CallProcedureSCRAPPOST);
LDSM004Route.route('/getSendMailProc').post(authenticationMiddleware.bearer, controller.SendMailProc);
LDSM004Route.route('/getUpdateMailTag').post(authenticationMiddleware.bearer, controller.UpdateMailTag);
LDSM004Route.route('/getMotherCoil').post(authenticationMiddleware.bearer, controller.GetMotherCoil);
LDSM004Route.route('/getFetchParCoil').post(authenticationMiddleware.bearer, controller.FetchParCoil);
LDSM004Route.route('/getBatchIds').post(authenticationMiddleware.bearer, controller.GetBatchIds);
LDSM004Route.route('/getMat_type').post(authenticationMiddleware.bearer, controller.GetMat_type);
LDSM004Route.route('/getSelectedRsnCat').post(authenticationMiddleware.bearer, controller.GetSelectedRsnCat);
LDSM004Route.route('/getPopMsgData').post(authenticationMiddleware.bearer, controller.PopMsgData);
LDSM004Route.route('/getReqIdGeneration').post(authenticationMiddleware.bearer, controller.ReqIdGeneration);
LDSM004Route.route('/getSetWtAdj').post(authenticationMiddleware.bearer, controller.SetWtAdj);
LDSM004Route.route('/getChkLoc').post(authenticationMiddleware.bearer, controller.ChkLoc);
LDSM004Route.route('/getP_INSERT_LP').post(authenticationMiddleware.bearer, controller.P_INSERT_LP);
LDSM004Route.route('/getMatDtlsLP').post(authenticationMiddleware.bearer, controller.GetMatDtlsLP);
LDSM004Route.route('/getBundleId').post(authenticationMiddleware.bearer, controller.GetBundleId);
LDSM004Route.route('/getQtyForLP').post(authenticationMiddleware.bearer, controller.GetQtyForLP);
LDSM004Route.route('/getBatchDtlforLP').post(authenticationMiddleware.bearer, controller.GetBatchDtlforLP);
LDSM004Route.route('/insertCoilDetails').post(authenticationMiddleware.bearer, controller.insertCoilDetails);
LDSM004Route.route('/modifyCoilDetails').post(authenticationMiddleware.bearer, controller.modifyCoilDetails);
LDSM004Route.route('/getRsnDetails').post(authenticationMiddleware.bearer, controller.getHoldRsnDetails);
LDSM004Route.route('/getBatchCount').post(authenticationMiddleware.bearer, controller.getBatchCount);
LDSM004Route.route('/getScrapProductionTable').post(authenticationMiddleware.bearer, controller.getScrapProductionTable);
LDSM004Route.route('/getScrapBatchId').post(authenticationMiddleware.bearer, controller.getScrapBatchId);
LDSM004Route.route('/getWorkCenterDropdown').post(authenticationMiddleware.bearer, controller.getWorkCenterList);
LDSM004Route.route('/getProductionType').post(authenticationMiddleware.bearer, controller.getProductionType);
LDSM004Route.route('/getWorkCenter').post(authenticationMiddleware.bearer, controller.getWorkCenter);
LDSM004Route.route('/getShiftStatus').post(authenticationMiddleware.bearer, controller.getShiftStatus);
LDSM004Route.route('/getPdiDtlSingleLot').post(authenticationMiddleware.bearer, controller.GetPdiDtlSingleLot);
LDSM004Route.route('/getPdiDtlMultiLot').post(authenticationMiddleware.bearer, controller.GetPdiDtlMultiLot);
LDSM004Route.route('/getCRTScheduleMerge').post(authenticationMiddleware.bearer, controller.CRTScheduleMerge);
LDSM004Route.route('/getNoMergeDetails').post(authenticationMiddleware.bearer, controller.noMergeDetails);
LDSM004Route.route('/getRollingLen').post(authenticationMiddleware.bearer, controller.getRollingLen);
LDSM004Route.route('/getLengthList').post(authenticationMiddleware.bearer, controller.getLengthList);
LDSM004Route.route('/getMbatch').post(authenticationMiddleware.bearer, controller.getMotherBatch);
LDSM004Route.route('/getpphProductName').post(authenticationMiddleware.bearer, controller.getProductName);
LDSM004Route.route('/getPieceActl').post(authenticationMiddleware.bearer, controller.GetPieceActl);
LDSM004Route.route('/getBatchstatuscn').post(authenticationMiddleware.bearer, controller.getBatchstatuscn);
LDSM004Route.route('/scrapmatno').post(authenticationMiddleware.bearer, controller.getScrapMatNo);
LDSM004Route.route('/getIntrmMatl').post(authenticationMiddleware.bearer, controller.getIntrmMatl);
LDSM004Route.route('/getUserIdsEditableMass').post(authenticationMiddleware.bearer, controller.getUserIdsEditableMass);
LDSM004Route.route('/getPrevRecorder').post(authenticationMiddleware.bearer, controller.getPrevRecorder);



export default LDSM004Route;