import { Router } from "express"; //
import * as controller from "../controllers/TSMCSSF001Controller";
import authenticationMiddleware from "../middlewares/authenticationMiddleware";

const postsRoute = Router();

postsRoute
  .route("/divisonList")
  .post(
    authenticationMiddleware.bearer,
    controller.divisonList
  );
postsRoute
  .route("/getDepartmentList")
  .post(
    authenticationMiddleware.bearer,
    controller.getDepartmentList
  );
postsRoute
  .route("/getSectionList")
  .post(
    authenticationMiddleware.bearer,
    controller.getSectionList
  );
postsRoute
  .route("/plantList")
  .post(
    authenticationMiddleware.bearer,
    controller.plantList
  );
  postsRoute
  .route("/getSHEMasterList")
  .post(
    authenticationMiddleware.bearer,
    controller.getSHEMasterList
  );
  postsRoute
  .route("/getSHEMatrixDetails")
  .post(
    authenticationMiddleware.bearer,
    controller.getSHEMatrixDetails
  );
  postsRoute
  .route("/ownersList")
  .post(
    authenticationMiddleware.bearer,
    controller.ownersList
  );
  postsRoute
  .route("/updateshematrixdetailsdata")
  .post(
    authenticationMiddleware.bearer,
    controller.updateshematrixdetailsdata
  );
  postsRoute
  .route("/getAuthUserForSHEMatrix")
  .post(
    authenticationMiddleware.bearer,
    controller.getAuthUserForSHEMatrix
  );
  postsRoute
  .route("/getSHEMatrixDeatilsDataListByRiskID")
  .post(
    authenticationMiddleware.bearer,
    controller.getSHEMatrixDeatilsDataListByRiskID
  );
  postsRoute
  .route("/getRiskDataList")
  .post(
    authenticationMiddleware.bearer,
    controller.getRiskDataList
  );
  postsRoute
  .route("/getSHEMatrixChartDetails")
  .post(
    authenticationMiddleware.bearer,
    controller.getSHEMatrixChartDetails
  );
  postsRoute
  .route("/getSHEMatrixResidualChartDetails")
  .post(
    authenticationMiddleware.bearer,
    controller.getSHEMatrixResidualChartDetails
  );
  postsRoute
  .route("/getPendingSHEMatrixDetails")
  .post(
    authenticationMiddleware.bearer,
    controller.getPendingSHEMatrixDetails
  );
  postsRoute
  .route("/getALLSHEMatrixDetails")
  .post(
    authenticationMiddleware.bearer,
    controller.getALLSHEMatrixDetails
  );
  postsRoute
  .route("/updateapprovalshematrixdetailsdata")
  .post(
    authenticationMiddleware.bearer,
    controller.updateapprovalshematrixdetailsdata
  );
  postsRoute
  .route("/insertSHEMatrixData")
  .post(
    authenticationMiddleware.bearer,
    controller.insertSHEMatrixData
  );
  postsRoute
  .route("/getEmployeeDetailsByPersonalNumber")
  .post(
    authenticationMiddleware.bearer,
    controller.getEmployeeDetailsByPersonalNumber
  );
  postsRoute
  .route("/uploadfiles")
  .post(
    authenticationMiddleware.bearer,
    controller.uploadfiles
  );
  postsRoute
  .route("/getDefaultRiskOwner")
  .post(
    authenticationMiddleware.bearer,
    controller.getDefaultRiskOwner
  );
  postsRoute
  .route("/UpdateSHEMatrixRejectedData")
  .post(
    authenticationMiddleware.bearer,
    controller.UpdateSHEMatrixRejectedData
  );
  postsRoute
  .route("/getPendingResidualSHEMatrixDetails")
  .post(
    authenticationMiddleware.bearer,
    controller.getPendingResidualSHEMatrixDetails
  );
  postsRoute
  .route("/updateDCIapprovalshematrixdetailsdata")
  .post(
    authenticationMiddleware.bearer,
    controller.updateDCIapprovalshematrixdetailsdata
  );
  postsRoute
  .route("/getApproverSectionList")
  .post(
    authenticationMiddleware.bearer,
    controller.getApproverSectionList
  );
  postsRoute
  .route("/getSHEMatrixDeatilsDataListByRISKChart")
  .post(
    authenticationMiddleware.bearer,
    controller.getSHEMatrixDeatilsDataListByRISKChart
  );
  postsRoute
  .route("/filedownload")
  .post(
    authenticationMiddleware.bearer,
    controller.filedownload
  );
export default postsRoute;
